#!/bin/bash -l

# load modules and run analysis pipeline
module load python/3.6.2
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
python $SCRIPTPATH/src/Pipeline.py
source $SCRIPTPATH/src/pipeline.sh

#close interactive session
exit
