project_name <- 'Matt Test#2';
working_dir <- '/projectnb/cnsbomic/Matt/Test Run'; # Directory for analysis and where data is 
annotation_filename <- '/projectnb/cnsbomic/Matt/Test Run/AnnotationML20180530.xlsx';
saveXlsx <- TRUE;
enrichr_section <- TRUE;
gsea_section <- TRUE;
enrichment_map <- TRUE;
map_color <- 'viridis';
species <- 'Human';
norm_method <- 'loess';
newcontrastonly <- FALSE;
txtFolder <- FALSE;
isInteractive <- TRUE;
notebook_dir <- '/project/cnsbomic/Omics_Notebook/src';
runDifferential <- TRUE;
enrichmentmap_p_val <- 0.05;
enrichmentmap_q_val <- 0.30;
zero_percent <- 0.70;
adjpcutoff <- 0.05;
BUSCC <- TRUE;
